"""Bundled sample datasets — generated by scripts/make_sample.py.

Embedded as a module so the Pyodide build can load any demo dataset without a
second network request. Five tables from different fields, each with a clear
quantitative relationship to explore. Do not edit by hand.
"""

CULTIVOS_CSV = '''Parcela,Region,Variedad,Riego,Riego_mm,Fertilizante_kg_ha,Temp_media_C,Horas_sol,Rendimiento_ton_ha
P-001,Norte,Sembra,Gravedad,368.0,153.3,17.7,10.63,6.37
P-002,Litoral,Aurora,Gravedad,601.8,209.2,21.3,7.21,7.39
P-003,Litoral,Kirán,Aspersión,527.3,201.5,25.4,8.48,7.03
P-004,Norte,Aurora,Gravedad,356.2,196.2,16.3,7.74,7.01
P-005,Sur,Sembra,Goteo,357.3,191.6,20.9,8.87,7.2
P-006,Norte,Sembra,Goteo,358.0,187.2,15.3,7.04,7.36
P-007,Sur,Sembra,Aspersión,520.1,92.6,23.8,5.7,5.46
P-008,Sur,Aurora,Gravedad,597.1,168.7,22.9,6.37,6.81
P-009,Norte,Aurora,Gravedad,432.4,202.9,14.8,8.15,7.11
P-010,Litoral,Sembra,Aspersión,674.0,86.9,24.3,7.63,5.47
P-011,Norte,Aurora,Aspersión,413.9,163.1,16.7,6.82,6.29
P-012,Centro,Kirán,Gravedad,532.2,130.7,22.4,7.59,6.01
P-013,Norte,Kirán,Aspersión,360.7,165.5,19.6,7.11,5.94
P-014,Centro,Sembra,Gravedad,493.7,121.4,21.8,6.14,6.17
P-015,Sur,Sembra,Aspersión,554.3,128.2,25.0,6.83,5.98
P-016,Norte,Sembra,Goteo,389.5,154.5,16.8,8.43,6.56
P-017,Sur,Sembra,Aspersión,454.3,153.2,22.5,8.46,6.46
P-018,Sur,Sembra,Goteo,502.8,131.6,23.2,8.41,6.27
P-019,Litoral,Sembra,Gravedad,620.7,167.6,24.6,8.82,7.62
P-020,Centro,Aurora,Aspersión,482.5,195.1,19.4,8.22,6.79
P-021,Centro,Kirán,Aspersión,531.7,113.4,20.5,6.54,5.13
P-022,Litoral,Aurora,Aspersión,617.6,135.2,22.6,7.72,6.19
P-023,Norte,Aurora,Gravedad,502.4,139.0,17.6,9.17,6.79
P-024,Centro,Kirán,Gravedad,371.9,184.1,17.1,8.82,5.92
P-025,Sur,Aurora,Aspersión,427.4,136.1,20.0,6.51,5.6
P-026,Litoral,Aurora,Goteo,579.7,202.4,23.3,8.7,7.64
P-027,Litoral,Aurora,Gravedad,588.1,196.4,27.3,7.46,7.29
P-028,Norte,Kirán,Gravedad,332.5,122.6,19.2,6.95,4.91
P-029,Norte,Sembra,Goteo,401.4,121.8,15.6,4.44,5.28
P-030,Centro,Kirán,Goteo,360.5,158.5,16.5,7.6,5.83
P-031,Norte,Kirán,Gravedad,505.6,183.0,17.5,6.51,6.03
P-032,Centro,Sembra,Goteo,499.0,221.7,17.6,6.19,7.44
P-033,Litoral,Aurora,Goteo,613.6,114.5,25.3,7.61,5.36
P-034,Centro,Sembra,Goteo,521.1,189.0,18.0,7.77,7.78
P-035,Sur,Aurora,Aspersión,522.2,139.7,22.3,6.36,6.1
P-036,Sur,Aurora,Gravedad,459.4,234.1,22.1,8.89,7.85
P-037,Norte,Aurora,Goteo,356.9,190.2,14.3,6.51,6.78
P-038,Litoral,Kirán,Gravedad,635.9,135.5,21.9,7.02,5.77
P-039,Norte,Kirán,Gravedad,391.6,134.4,15.6,6.78,5.47
P-040,Centro,Aurora,Gravedad,534.6,144.5,18.8,6.5,5.91
P-041,Sur,Sembra,Aspersión,517.5,173.1,22.0,6.08,6.85
P-042,Norte,Kirán,Aspersión,338.7,129.2,14.6,7.66,5.16
P-043,Norte,Aurora,Aspersión,269.8,125.3,16.2,7.48,5.2
P-044,Sur,Aurora,Gravedad,488.1,115.2,21.6,7.21,5.3
P-045,Litoral,Sembra,Aspersión,597.1,139.4,21.2,7.69,6.34
P-046,Sur,Kirán,Gravedad,404.4,134.0,26.9,8.67,5.87
P-047,Norte,Sembra,Goteo,349.7,158.5,20.8,7.07,6.37
P-048,Litoral,Kirán,Goteo,535.5,145.9,24.7,7.95,5.93
P-049,Norte,Aurora,Goteo,448.4,119.5,16.7,6.71,5.75
P-050,Litoral,Sembra,Gravedad,642.8,149.7,19.8,7.92,6.96
P-051,Norte,Kirán,Aspersión,468.0,165.6,19.4,8.11,6.33
P-052,Litoral,Sembra,Aspersión,676.3,134.1,25.7,6.63,6.03
P-053,Norte,Aurora,Aspersión,356.3,113.5,16.4,6.24,5.0
P-054,Litoral,Kirán,Goteo,680.9,185.0,26.2,7.77,6.93
P-055,Sur,Aurora,Gravedad,436.3,139.5,23.1,7.02,6.11
P-056,Norte,Sembra,Goteo,416.5,71.0,17.2,6.36,4.46
P-057,Sur,Aurora,Gravedad,469.7,232.2,23.8,9.08,7.68
P-058,Centro,Sembra,Aspersión,545.4,115.6,19.7,6.68,5.82
P-059,Litoral,Kirán,Goteo,677.1,185.9,23.9,9.02,7.5
P-060,Norte,Kirán,Gravedad,280.9,221.1,17.4,7.93,6.53
P-061,Litoral,Aurora,Aspersión,568.8,135.6,22.0,8.18,6.18
P-062,Litoral,Kirán,Gravedad,695.2,158.3,25.8,7.69,6.8
P-063,Litoral,Sembra,Gravedad,513.0,192.4,23.0,7.51,7.27
P-064,Centro,Kirán,Goteo,573.8,183.0,19.9,7.99,6.77
P-065,Litoral,Aurora,Gravedad,519.6,194.5,26.0,7.38,6.88
P-066,Sur,Aurora,Gravedad,528.0,76.5,25.6,7.03,4.58
P-067,Centro,Aurora,Goteo,357.8,118.1,19.0,8.53,5.4
P-068,Sur,Kirán,Goteo,498.7,228.2,21.7,8.65,7.53
P-069,Litoral,Kirán,Goteo,535.7,159.5,23.5,8.03,6.52
P-070,Sur,Sembra,Gravedad,593.5,105.3,22.1,7.91,6.05
P-071,Litoral,Kirán,Goteo,562.9,177.2,24.3,6.21,6.2
P-072,Norte,Kirán,Aspersión,365.0,184.6,14.7,7.42,6.72
P-073,Centro,Sembra,Gravedad,323.1,179.3,22.5,7.4,6.38
P-074,Centro,Aurora,Aspersión,467.6,187.5,18.2,8.93,6.97
P-075,Norte,Sembra,Aspersión,316.4,155.2,14.4,6.19,5.72
P-076,Litoral,Sembra,Gravedad,506.0,225.1,23.8,5.43,7.92
P-077,Litoral,Sembra,Aspersión,612.1,195.5,25.3,7.03,7.61
P-078,Sur,Kirán,Aspersión,518.0,101.6,19.4,7.01,5.69
P-079,Litoral,Kirán,Gravedad,650.3,92.8,25.0,7.4,5.2
P-080,Norte,Aurora,Gravedad,264.2,178.0,17.3,8.04,6.55
P-081,Centro,Sembra,Goteo,442.6,124.9,21.5,6.38,6.11
P-082,Litoral,Aurora,Gravedad,637.8,163.2,23.7,8.14,6.77
P-083,Sur,Aurora,Goteo,561.9,120.0,24.1,6.77,6.14
P-084,Centro,Kirán,Goteo,496.2,220.4,21.3,5.46,7.1
P-085,Sur,Aurora,Aspersión,525.1,201.8,21.1,7.51,7.34
P-086,Norte,Kirán,Goteo,426.3,166.8,15.9,7.02,5.94
P-087,Sur,Kirán,Aspersión,400.8,181.3,18.7,8.15,6.52
P-088,Norte,Aurora,Goteo,367.3,127.4,18.9,7.35,6.02
P-089,Centro,Aurora,Aspersión,464.3,139.3,19.4,6.96,6.29
P-090,Norte,Aurora,Aspersión,335.7,123.5,19.7,6.96,5.19
P-091,Centro,Aurora,Aspersión,503.6,136.1,18.5,8.29,6.34
P-092,Centro,Sembra,Aspersión,465.2,213.4,21.3,7.91,7.77
P-093,Norte,Kirán,Goteo,457.2,130.2,20.0,7.62,5.91
P-094,Sur,Aurora,Goteo,519.2,123.6,26.1,7.07,5.91
P-095,Sur,Kirán,Gravedad,619.5,167.3,20.0,9.19,6.51
P-096,Sur,Kirán,Gravedad,535.4,94.9,22.8,7.33,5.03
P-097,Litoral,Sembra,Aspersión,549.5,137.1,26.9,7.86,6.79
P-098,Litoral,Sembra,Aspersión,578.0,160.7,28.8,8.04,6.91
P-099,Litoral,Kirán,Goteo,682.9,214.8,25.1,8.97,7.86
P-100,Norte,Aurora,Gravedad,413.0,180.7,19.7,7.16,6.35
P-101,Norte,Sembra,Gravedad,321.8,115.3,18.2,7.24,5.45
P-102,Norte,Sembra,Goteo,240.5,115.1,18.9,7.09,4.93
P-103,Sur,Kirán,Aspersión,626.5,79.3,21.1,8.63,5.41
P-104,Norte,Sembra,Aspersión,353.6,121.2,17.6,7.35,5.72
P-105,Norte,Aurora,Goteo,411.1,255.6,23.6,8.82,8.15
P-106,Norte,Kirán,Gravedad,521.7,171.1,20.7,8.55,6.29
P-107,Litoral,Aurora,Gravedad,618.8,141.7,23.8,7.73,6.16
P-108,Norte,Aurora,Goteo,426.4,135.8,15.5,8.52,5.52
P-109,Centro,Kirán,Goteo,433.2,149.0,20.0,8.15,5.76
P-110,Norte,Kirán,Gravedad,339.3,118.5,17.7,8.38,5.19
P-111,Litoral,Kirán,Goteo,659.1,157.2,26.5,9.85,7.07
P-112,Norte,Kirán,Goteo,434.1,96.7,18.3,8.57,4.78
P-113,Centro,Kirán,Aspersión,448.4,169.5,21.9,7.99,6.06
P-114,Centro,Kirán,Aspersión,390.3,219.0,16.5,6.22,6.44
P-115,Sur,Aurora,Gravedad,467.5,98.6,22.7,8.31,4.88
P-116,Centro,Kirán,Aspersión,341.3,138.3,16.2,7.43,5.7
P-117,Norte,Kirán,Aspersión,340.8,158.6,17.5,7.8,6.0
P-118,Sur,Sembra,Gravedad,521.9,69.3,20.5,7.89,4.82
P-119,Centro,Aurora,Aspersión,467.9,142.7,17.9,7.03,6.07
P-120,Litoral,Aurora,Aspersión,794.2,194.7,23.9,7.09,7.64
P-121,Sur,Sembra,Aspersión,518.5,145.8,25.1,7.98,6.81
P-122,Litoral,Kirán,Gravedad,723.6,151.9,23.7,7.71,6.8
P-123,Sur,Sembra,Goteo,506.5,93.1,23.3,6.24,5.51
P-124,Litoral,Aurora,Aspersión,693.1,185.5,26.7,7.84,7.34
P-125,Norte,Sembra,Gravedad,455.7,241.1,13.9,7.43,7.78
P-126,Litoral,Kirán,Gravedad,592.7,193.5,24.6,7.67,7.07
P-127,Norte,Aurora,Gravedad,431.2,144.8,14.6,9.02,6.2
P-128,Norte,Aurora,Gravedad,322.9,103.7,19.3,7.33,4.99
P-129,Centro,Aurora,Gravedad,409.8,114.3,20.8,7.32,5.59
P-130,Centro,Kirán,Goteo,479.6,220.5,16.1,7.36,7.22
P-131,Norte,Kirán,Goteo,456.2,149.0,18.4,5.22,5.41
P-132,Norte,Aurora,Gravedad,445.7,107.3,14.3,8.69,5.35
P-133,Norte,Kirán,Aspersión,519.1,182.9,16.9,6.84,6.75
P-134,Litoral,Kirán,Gravedad,639.3,113.0,21.7,7.06,5.74
P-135,Centro,Aurora,Goteo,415.9,172.6,18.2,8.29,6.4
P-136,Litoral,Aurora,Aspersión,588.8,164.6,25.4,7.77,6.85
P-137,Norte,Aurora,Goteo,568.3,206.2,17.9,5.53,7.12
P-138,Centro,Aurora,Aspersión,377.3,150.3,18.6,9.89,6.36
P-139,Sur,Kirán,Goteo,435.1,124.0,21.7,8.07,5.65
P-140,Litoral,Aurora,Goteo,625.3,148.3,23.2,7.74,6.59
'''

SALUD_CSV = '''Paciente,Sexo,Grupo_edad,Actividad_fisica,Edad,IMC,Colesterol_mg_dl,Horas_sueno,Presion_sistolica
PAC-001,Femenino,18-34,Alta,19,27.1,187.2,6.3,122.4
PAC-002,Masculino,65+,Baja,66,34.0,245.2,6.3,180.5
PAC-003,Femenino,35-49,Media,35,25.7,198.1,5.5,128.7
PAC-004,Femenino,35-49,Baja,49,23.8,183.1,8.9,135.2
PAC-005,Femenino,18-34,Media,31,31.5,184.7,6.0,129.2
PAC-006,Femenino,65+,Alta,67,30.4,235.9,8.9,146.8
PAC-007,Femenino,50-64,Baja,52,28.1,192.3,8.1,143.5
PAC-008,Femenino,50-64,Baja,64,33.9,217.8,8.0,165.6
PAC-009,Masculino,50-64,Media,53,24.5,193.4,6.2,149.2
PAC-010,Masculino,18-34,Alta,18,23.9,194.8,4.9,115.1
PAC-011,Femenino,35-49,Alta,38,27.7,191.8,7.1,142.8
PAC-012,Masculino,18-34,Media,27,26.0,170.4,8.3,126.8
PAC-013,Masculino,50-64,Media,62,23.0,181.4,7.1,159.2
PAC-014,Femenino,65+,Baja,69,34.3,243.2,5.5,165.6
PAC-015,Masculino,50-64,Media,63,26.3,173.5,8.6,152.9
PAC-016,Masculino,18-34,Baja,32,28.6,176.2,6.6,126.7
PAC-017,Femenino,50-64,Media,56,26.5,192.9,5.7,153.2
PAC-018,Masculino,50-64,Media,63,30.7,206.3,7.9,161.6
PAC-019,Masculino,18-34,Baja,25,27.0,168.7,7.7,124.9
PAC-020,Masculino,18-34,Alta,34,22.2,188.6,6.7,134.6
PAC-021,Femenino,50-64,Baja,57,31.2,197.3,6.8,150.7
PAC-022,Masculino,35-49,Alta,41,25.5,204.8,7.2,123.3
PAC-023,Masculino,18-34,Baja,21,34.1,186.3,6.5,138.4
PAC-024,Femenino,18-34,Media,31,29.1,157.6,7.0,135.3
PAC-025,Masculino,65+,Media,68,30.4,222.8,6.5,162.4
PAC-026,Masculino,50-64,Media,52,29.9,212.5,9.0,148.7
PAC-027,Masculino,50-64,Media,52,24.4,184.0,8.0,139.7
PAC-028,Femenino,50-64,Alta,64,27.3,218.4,5.6,152.6
PAC-029,Masculino,18-34,Alta,25,23.8,195.3,7.1,111.7
PAC-030,Femenino,65+,Baja,74,35.1,243.6,5.5,174.9
PAC-031,Masculino,50-64,Alta,64,21.9,200.3,8.7,144.4
PAC-032,Femenino,35-49,Media,47,27.6,187.1,7.5,148.5
PAC-033,Femenino,50-64,Baja,62,26.9,220.5,8.4,155.0
PAC-034,Femenino,18-34,Media,31,19.7,164.1,5.6,132.8
PAC-035,Masculino,35-49,Media,46,21.9,150.0,7.3,140.1
PAC-036,Femenino,50-64,Alta,64,24.8,194.9,6.1,144.7
PAC-037,Femenino,65+,Baja,75,34.2,253.2,8.2,178.4
PAC-038,Masculino,50-64,Media,58,24.4,197.9,6.8,154.4
PAC-039,Masculino,65+,Baja,71,31.2,212.1,9.5,164.1
PAC-040,Femenino,35-49,Alta,44,26.0,164.8,8.3,124.6
PAC-041,Masculino,18-34,Baja,19,25.8,156.8,5.7,123.5
PAC-042,Femenino,50-64,Baja,51,27.1,196.2,6.2,146.5
PAC-043,Masculino,50-64,Media,56,25.9,230.8,7.4,153.7
PAC-044,Femenino,50-64,Media,55,22.8,186.8,6.3,144.2
PAC-045,Femenino,35-49,Media,38,27.6,172.2,5.2,134.1
PAC-046,Femenino,50-64,Alta,60,30.9,213.0,6.4,158.7
PAC-047,Masculino,18-34,Media,21,25.5,185.0,7.2,126.5
PAC-048,Masculino,50-64,Baja,58,31.7,225.1,6.9,161.3
PAC-049,Femenino,18-34,Media,20,25.9,156.5,7.6,115.1
PAC-050,Masculino,65+,Baja,78,30.3,263.4,5.9,176.2
PAC-051,Masculino,50-64,Alta,56,24.6,191.8,7.2,134.4
PAC-052,Femenino,65+,Alta,78,24.7,240.2,7.4,159.4
PAC-053,Femenino,65+,Baja,67,28.4,212.5,6.9,158.8
PAC-054,Femenino,35-49,Alta,43,22.9,195.3,8.4,134.2
PAC-055,Femenino,18-34,Baja,32,25.9,190.4,7.8,133.7
PAC-056,Masculino,50-64,Alta,57,27.3,221.6,7.9,143.6
PAC-057,Masculino,18-34,Baja,30,26.8,163.8,7.2,144.7
PAC-058,Femenino,35-49,Alta,48,23.0,198.9,5.8,141.1
PAC-059,Masculino,35-49,Alta,46,24.7,177.2,7.1,131.4
PAC-060,Masculino,18-34,Baja,32,31.8,182.3,6.8,148.1
PAC-061,Masculino,65+,Baja,74,27.4,218.9,7.6,179.1
PAC-062,Femenino,50-64,Media,64,26.7,217.8,7.1,150.1
PAC-063,Masculino,65+,Media,70,30.6,221.4,6.0,155.1
PAC-064,Femenino,18-34,Media,31,22.7,173.8,7.7,133.1
PAC-065,Masculino,65+,Baja,74,26.0,200.4,7.2,165.8
PAC-066,Femenino,50-64,Baja,57,32.0,193.9,7.0,158.3
PAC-067,Femenino,65+,Media,79,28.1,238.2,7.3,174.0
PAC-068,Femenino,18-34,Media,30,27.4,177.4,7.3,127.9
PAC-069,Masculino,35-49,Alta,45,27.1,204.1,7.9,134.6
PAC-070,Masculino,65+,Baja,73,35.1,237.2,7.7,174.3
PAC-071,Femenino,65+,Alta,65,20.8,218.4,7.7,148.4
PAC-072,Femenino,18-34,Media,25,25.4,157.1,7.2,124.8
PAC-073,Masculino,50-64,Baja,56,25.4,210.1,5.8,159.1
PAC-074,Masculino,65+,Baja,79,29.2,241.7,7.7,180.6
PAC-075,Femenino,18-34,Media,34,23.2,175.6,6.7,117.2
PAC-076,Masculino,18-34,Baja,19,39.2,164.4,9.0,141.6
PAC-077,Femenino,18-34,Media,28,27.6,193.0,6.7,131.3
PAC-078,Femenino,65+,Baja,66,27.5,177.0,8.4,141.5
PAC-079,Masculino,65+,Baja,77,33.2,214.9,7.5,167.2
PAC-080,Masculino,35-49,Baja,48,28.5,191.6,6.1,153.6
PAC-081,Femenino,35-49,Media,36,23.1,200.7,7.0,127.0
PAC-082,Masculino,18-34,Baja,19,28.5,177.4,5.6,133.9
PAC-083,Masculino,65+,Media,69,26.6,208.6,6.5,145.7
PAC-084,Femenino,18-34,Baja,24,28.4,163.5,5.1,132.0
PAC-085,Femenino,18-34,Baja,28,27.9,193.9,7.0,127.1
PAC-086,Masculino,18-34,Media,19,21.5,172.8,5.9,116.7
PAC-087,Femenino,50-64,Alta,61,23.3,209.7,6.6,145.4
PAC-088,Masculino,50-64,Baja,59,31.3,185.0,7.2,158.7
PAC-089,Femenino,50-64,Baja,59,29.6,223.5,6.5,150.3
PAC-090,Femenino,65+,Media,76,29.2,221.1,6.9,161.7
PAC-091,Masculino,65+,Baja,79,29.4,240.9,6.8,174.4
PAC-092,Masculino,35-49,Media,47,28.9,173.5,5.4,150.8
PAC-093,Masculino,35-49,Media,43,32.7,201.8,8.2,147.2
PAC-094,Femenino,50-64,Media,53,24.9,215.3,6.2,150.2
PAC-095,Femenino,18-34,Media,32,22.9,209.2,7.8,140.2
PAC-096,Femenino,65+,Media,70,30.4,243.9,5.9,159.2
PAC-097,Femenino,50-64,Baja,57,28.7,231.7,6.7,152.7
PAC-098,Femenino,50-64,Media,63,24.7,197.1,7.4,142.4
PAC-099,Femenino,50-64,Baja,61,31.6,238.5,6.2,160.7
PAC-100,Masculino,65+,Media,76,25.9,247.9,9.3,166.8
PAC-101,Femenino,50-64,Baja,56,33.4,231.4,7.5,153.6
PAC-102,Femenino,50-64,Baja,52,26.8,177.5,4.8,143.6
PAC-103,Femenino,65+,Alta,77,24.2,207.6,8.2,145.5
PAC-104,Femenino,50-64,Baja,61,33.0,202.5,7.7,162.7
PAC-105,Masculino,18-34,Alta,26,24.2,167.1,6.7,125.6
PAC-106,Femenino,35-49,Media,39,34.9,201.0,6.6,149.8
PAC-107,Masculino,65+,Baja,67,26.2,174.6,7.8,160.2
PAC-108,Masculino,65+,Baja,76,31.0,226.0,6.3,172.3
PAC-109,Masculino,50-64,Media,53,16.7,149.0,6.2,143.1
PAC-110,Masculino,50-64,Media,51,21.6,191.8,8.1,136.5
PAC-111,Femenino,18-34,Baja,28,29.7,184.7,7.6,135.0
PAC-112,Masculino,18-34,Baja,24,27.0,180.8,5.1,130.2
PAC-113,Femenino,18-34,Media,29,24.3,144.2,7.0,131.6
PAC-114,Masculino,35-49,Media,44,24.7,163.2,7.6,141.8
PAC-115,Femenino,65+,Alta,67,23.3,153.3,7.1,139.6
PAC-116,Masculino,18-34,Baja,27,33.8,201.1,7.8,147.6
PAC-117,Femenino,35-49,Media,35,23.1,131.4,7.8,123.1
PAC-118,Femenino,65+,Baja,77,29.1,260.4,7.7,165.6
PAC-119,Femenino,35-49,Baja,44,33.9,224.1,7.5,149.4
PAC-120,Femenino,65+,Media,65,25.6,207.0,6.5,142.4
PAC-121,Masculino,65+,Media,78,30.2,232.3,4.9,167.1
PAC-122,Femenino,35-49,Baja,41,31.1,175.4,5.3,155.1
PAC-123,Femenino,50-64,Alta,59,26.7,217.8,6.3,147.9
PAC-124,Femenino,65+,Baja,74,25.7,200.9,7.7,156.7
PAC-125,Masculino,18-34,Baja,23,30.0,189.7,7.1,126.7
PAC-126,Masculino,18-34,Alta,18,20.0,144.5,7.3,109.0
PAC-127,Masculino,18-34,Media,20,20.5,169.0,6.8,118.7
PAC-128,Masculino,65+,Alta,70,29.7,218.9,6.3,165.5
PAC-129,Femenino,35-49,Baja,45,29.4,201.3,7.7,140.1
PAC-130,Femenino,50-64,Baja,54,31.0,224.7,6.4,152.1
PAC-131,Masculino,18-34,Media,20,21.0,150.9,9.0,119.0
PAC-132,Masculino,50-64,Baja,61,26.6,195.6,5.5,161.2
PAC-133,Femenino,18-34,Baja,22,30.6,162.2,8.8,130.7
PAC-134,Masculino,18-34,Media,23,23.1,143.4,6.4,130.0
PAC-135,Femenino,65+,Alta,75,27.6,246.5,7.8,150.8
PAC-136,Masculino,50-64,Media,64,25.4,207.8,6.5,156.5
PAC-137,Masculino,18-34,Media,32,27.2,180.5,4.4,142.7
PAC-138,Masculino,18-34,Media,32,28.0,179.9,8.7,136.3
PAC-139,Masculino,65+,Media,76,24.4,219.7,7.4,162.8
PAC-140,Masculino,18-34,Media,18,21.4,156.8,7.7,116.2
PAC-141,Masculino,65+,Alta,68,21.5,194.6,7.2,147.9
PAC-142,Femenino,18-34,Media,26,28.9,158.2,7.6,134.3
PAC-143,Femenino,35-49,Media,37,29.8,196.9,6.7,146.4
PAC-144,Masculino,65+,Media,79,21.6,216.3,4.8,164.7
PAC-145,Femenino,65+,Alta,70,27.9,214.1,6.7,166.2
PAC-146,Masculino,35-49,Baja,37,25.0,216.0,8.2,133.3
PAC-147,Femenino,18-34,Media,33,22.8,173.6,7.5,130.8
PAC-148,Femenino,18-34,Baja,26,25.2,151.9,7.6,135.8
PAC-149,Masculino,65+,Alta,77,29.5,203.5,6.7,158.9
PAC-150,Femenino,18-34,Baja,19,29.3,179.2,7.7,118.7
'''

EDUCACION_CSV = '''Estudiante,Carrera,Jornada,Beca,Horas_estudio_sem,Asistencia_pct,Horas_pantalla_dia,Puntaje_final
EST-001,Economía,Vespertina,No,3.6,86.1,3.8,52.5
EST-002,Enfermería,Diurna,No,14.5,75.3,1.8,67.3
EST-003,Enfermería,Diurna,Sí,11.3,95.0,1.2,78.3
EST-004,Ingeniería,Vespertina,No,10.0,92.2,4.8,50.6
EST-005,Economía,Diurna,No,12.4,94.2,1.9,67.2
EST-006,Ingeniería,Diurna,Sí,8.3,62.2,4.0,55.4
EST-007,Enfermería,Diurna,No,20.4,93.7,6.2,77.1
EST-008,Economía,Diurna,Sí,13.2,73.4,3.5,66.8
EST-009,Biología,Diurna,No,11.1,76.8,6.4,50.9
EST-010,Enfermería,Diurna,Sí,14.8,67.0,3.9,72.2
EST-011,Ingeniería,Vespertina,No,5.8,88.7,3.5,56.4
EST-012,Economía,Diurna,Sí,4.4,90.8,3.3,60.2
EST-013,Economía,Vespertina,Sí,4.9,68.6,3.7,52.7
EST-014,Enfermería,Vespertina,Sí,14.8,70.4,5.4,70.2
EST-015,Enfermería,Diurna,Sí,18.2,81.4,5.6,79.1
EST-016,Economía,Vespertina,No,10.1,91.6,3.4,59.7
EST-017,Economía,Vespertina,Sí,7.0,94.8,4.1,62.5
EST-018,Biología,Vespertina,No,4.4,93.6,4.4,54.8
EST-019,Enfermería,Vespertina,Sí,14.5,85.8,2.9,75.2
EST-020,Ingeniería,Vespertina,No,12.1,71.8,2.8,60.0
EST-021,Ingeniería,Diurna,No,9.7,79.6,4.5,44.3
EST-022,Biología,Vespertina,Sí,6.1,90.7,4.4,55.2
EST-023,Biología,Diurna,No,12.0,72.8,3.4,59.0
EST-024,Enfermería,Diurna,Sí,10.6,81.0,3.1,66.2
EST-025,Ingeniería,Diurna,No,7.5,82.6,6.6,56.8
EST-026,Enfermería,Vespertina,Sí,13.2,82.1,1.9,79.6
EST-027,Ingeniería,Vespertina,Sí,11.0,89.0,4.2,69.2
EST-028,Enfermería,Diurna,No,7.3,71.9,3.8,48.3
EST-029,Biología,Diurna,No,9.4,81.5,5.4,59.2
EST-030,Ingeniería,Vespertina,No,12.3,91.4,5.5,58.6
EST-031,Ingeniería,Diurna,No,13.1,69.5,5.9,44.8
EST-032,Economía,Diurna,No,13.1,88.1,5.4,60.7
EST-033,Enfermería,Vespertina,Sí,6.5,87.9,4.5,57.4
EST-034,Ingeniería,Diurna,No,10.4,77.3,5.7,40.0
EST-035,Economía,Diurna,Sí,9.2,82.0,5.1,45.5
EST-036,Biología,Diurna,No,8.1,84.4,3.4,66.8
EST-037,Biología,Vespertina,No,17.4,76.7,5.0,64.7
EST-038,Ingeniería,Diurna,No,6.1,65.8,4.6,41.6
EST-039,Economía,Vespertina,No,6.1,89.2,3.0,63.7
EST-040,Ingeniería,Diurna,Sí,9.7,67.8,3.3,53.8
EST-041,Ingeniería,Diurna,No,14.8,69.1,2.7,66.6
EST-042,Ingeniería,Vespertina,Sí,10.5,83.0,4.0,61.2
EST-043,Ingeniería,Diurna,Sí,15.7,63.7,4.6,71.3
EST-044,Economía,Diurna,No,17.1,78.1,5.3,65.1
EST-045,Ingeniería,Diurna,No,20.5,96.6,3.9,78.6
EST-046,Ingeniería,Diurna,No,13.9,93.4,3.8,65.0
EST-047,Economía,Vespertina,No,8.7,80.3,3.9,55.4
EST-048,Biología,Diurna,Sí,11.9,88.3,5.7,60.6
EST-049,Enfermería,Diurna,No,11.5,85.7,2.9,68.3
EST-050,Biología,Vespertina,Sí,9.0,67.6,3.4,56.6
EST-051,Enfermería,Vespertina,No,9.0,66.9,5.0,54.5
EST-052,Biología,Diurna,No,15.5,98.1,3.2,75.9
EST-053,Ingeniería,Vespertina,No,5.0,94.5,3.3,59.5
EST-054,Biología,Diurna,No,8.3,76.2,4.3,50.8
EST-055,Ingeniería,Vespertina,Sí,5.6,80.7,3.3,56.6
EST-056,Enfermería,Diurna,No,14.8,89.0,2.5,73.4
EST-057,Biología,Diurna,Sí,25.4,83.0,4.8,78.5
EST-058,Biología,Diurna,Sí,22.9,83.6,3.1,77.9
EST-059,Economía,Vespertina,No,7.6,84.9,4.0,50.1
EST-060,Biología,Diurna,Sí,16.2,67.5,5.8,58.4
EST-061,Economía,Vespertina,No,11.0,82.1,3.9,61.2
EST-062,Enfermería,Vespertina,Sí,8.1,83.4,3.3,58.8
EST-063,Economía,Vespertina,Sí,10.1,84.0,3.8,65.3
EST-064,Enfermería,Diurna,No,18.4,65.0,3.3,67.3
EST-065,Ingeniería,Vespertina,No,14.7,65.1,3.3,54.4
EST-066,Enfermería,Vespertina,No,3.8,85.8,4.1,49.6
EST-067,Biología,Diurna,Sí,15.2,76.3,6.4,64.6
EST-068,Biología,Diurna,No,18.1,82.2,6.9,86.2
EST-069,Economía,Diurna,No,11.6,81.6,3.2,55.7
EST-070,Biología,Vespertina,Sí,5.3,83.2,4.7,52.5
EST-071,Economía,Diurna,No,16.3,85.1,5.4,69.7
EST-072,Economía,Vespertina,No,13.6,90.7,4.3,71.7
EST-073,Ingeniería,Vespertina,No,10.6,83.2,6.1,63.5
EST-074,Economía,Diurna,Sí,19.2,86.8,2.5,88.6
EST-075,Ingeniería,Diurna,No,8.4,79.7,4.3,55.3
EST-076,Enfermería,Diurna,No,18.5,96.1,5.2,84.0
EST-077,Ingeniería,Vespertina,Sí,9.5,95.0,6.7,51.9
EST-078,Enfermería,Vespertina,No,16.4,86.6,6.9,70.5
EST-079,Ingeniería,Vespertina,No,18.4,83.0,7.1,51.5
EST-080,Enfermería,Diurna,Sí,12.1,70.4,3.4,51.6
EST-081,Economía,Diurna,Sí,10.8,66.9,5.8,57.9
EST-082,Economía,Vespertina,No,10.2,75.2,4.3,55.3
EST-083,Biología,Vespertina,No,9.8,77.0,2.6,50.6
EST-084,Biología,Diurna,No,10.0,68.6,1.4,58.0
EST-085,Biología,Diurna,No,13.6,81.9,5.7,70.8
EST-086,Ingeniería,Diurna,No,19.0,87.5,7.7,68.5
EST-087,Biología,Diurna,No,13.5,83.2,3.3,72.3
EST-088,Ingeniería,Diurna,Sí,14.8,94.8,4.5,74.3
EST-089,Enfermería,Diurna,No,11.2,66.2,5.0,60.1
EST-090,Biología,Diurna,No,13.8,86.9,5.7,61.5
EST-091,Enfermería,Diurna,No,9.4,80.0,4.9,55.1
EST-092,Economía,Vespertina,Sí,6.8,81.2,5.5,56.7
EST-093,Economía,Diurna,No,15.2,77.7,5.1,66.8
EST-094,Enfermería,Diurna,Sí,5.3,76.6,3.4,57.4
EST-095,Ingeniería,Diurna,No,10.6,95.7,6.8,62.8
EST-096,Economía,Vespertina,No,7.8,83.6,6.3,52.5
EST-097,Biología,Vespertina,No,9.9,86.6,3.0,57.6
EST-098,Ingeniería,Diurna,Sí,17.5,73.8,2.6,75.8
EST-099,Economía,Vespertina,No,2.9,79.4,5.4,47.8
EST-100,Ingeniería,Diurna,No,14.4,87.4,4.2,66.0
EST-101,Ingeniería,Diurna,No,14.4,72.9,5.4,54.7
EST-102,Ingeniería,Diurna,No,15.3,86.1,4.1,80.1
EST-103,Enfermería,Diurna,Sí,13.6,82.4,4.0,72.6
EST-104,Biología,Diurna,Sí,14.6,81.1,4.3,65.7
EST-105,Biología,Diurna,Sí,16.3,83.8,3.2,81.4
EST-106,Biología,Vespertina,Sí,10.3,78.3,6.9,62.0
EST-107,Biología,Diurna,No,16.7,87.9,4.2,72.1
EST-108,Enfermería,Vespertina,Sí,5.2,72.6,1.7,58.6
EST-109,Economía,Diurna,Sí,16.2,87.3,4.6,76.4
EST-110,Biología,Diurna,No,7.6,94.2,8.0,48.3
EST-111,Biología,Vespertina,No,11.8,85.8,1.6,74.0
EST-112,Biología,Diurna,Sí,2.0,74.3,4.4,51.1
EST-113,Economía,Diurna,No,17.0,83.5,4.6,72.3
EST-114,Economía,Vespertina,No,10.3,74.8,6.1,51.6
EST-115,Ingeniería,Vespertina,Sí,11.6,96.3,2.4,72.7
EST-116,Biología,Diurna,Sí,16.8,85.5,6.4,70.6
EST-117,Biología,Diurna,No,12.6,86.3,3.4,66.3
EST-118,Economía,Vespertina,No,4.6,68.7,2.8,53.0
EST-119,Economía,Diurna,No,15.9,72.8,4.5,67.6
EST-120,Enfermería,Diurna,Sí,10.8,86.7,1.3,73.6
EST-121,Biología,Vespertina,Sí,9.9,80.1,6.7,63.6
EST-122,Enfermería,Diurna,No,7.9,83.9,4.4,49.9
EST-123,Enfermería,Vespertina,No,4.5,98.8,2.9,49.6
EST-124,Enfermería,Vespertina,No,4.0,84.8,3.2,53.8
EST-125,Ingeniería,Diurna,No,11.7,69.4,3.3,61.7
EST-126,Economía,Diurna,No,12.5,92.5,6.4,73.5
EST-127,Economía,Diurna,No,14.5,74.1,5.7,63.1
EST-128,Economía,Diurna,Sí,12.2,80.0,5.7,71.9
EST-129,Enfermería,Diurna,No,13.1,93.5,3.7,66.6
EST-130,Economía,Diurna,Sí,19.3,85.9,7.6,69.3
EST-131,Ingeniería,Diurna,No,15.3,95.5,4.8,75.0
EST-132,Enfermería,Diurna,Sí,7.3,82.7,3.4,63.8
EST-133,Biología,Vespertina,No,12.8,82.7,5.2,54.6
EST-134,Economía,Vespertina,No,5.7,78.9,2.4,58.1
EST-135,Economía,Diurna,No,12.3,97.5,4.8,61.2
EST-136,Enfermería,Diurna,Sí,19.2,86.5,5.5,83.9
EST-137,Economía,Vespertina,No,12.9,87.3,5.2,66.5
EST-138,Enfermería,Diurna,No,13.7,96.0,4.1,77.7
EST-139,Ingeniería,Vespertina,No,10.7,91.4,5.1,59.0
EST-140,Biología,Diurna,No,16.4,92.0,4.9,69.5
EST-141,Economía,Diurna,Sí,9.1,93.8,4.2,68.0
EST-142,Enfermería,Diurna,No,10.8,79.4,2.8,58.4
EST-143,Economía,Diurna,No,20.6,86.9,2.8,85.4
EST-144,Enfermería,Vespertina,Sí,7.9,90.9,3.0,64.6
EST-145,Enfermería,Vespertina,No,4.9,78.5,1.4,60.0
EST-146,Biología,Vespertina,No,5.2,64.9,3.4,46.7
EST-147,Economía,Diurna,Sí,18.4,66.8,3.2,78.9
EST-148,Enfermería,Vespertina,Sí,9.3,82.2,5.1,59.2
EST-149,Ingeniería,Diurna,No,18.6,68.9,5.5,59.1
EST-150,Economía,Diurna,No,2.1,90.5,3.7,56.1
EST-151,Ingeniería,Diurna,No,13.4,97.8,4.0,75.9
EST-152,Enfermería,Vespertina,Sí,8.7,87.4,1.8,75.1
EST-153,Economía,Vespertina,No,10.4,76.0,4.1,50.8
EST-154,Ingeniería,Diurna,No,10.1,88.3,6.2,59.3
EST-155,Ingeniería,Diurna,Sí,10.0,85.5,5.7,71.1
EST-156,Economía,Vespertina,No,6.9,90.8,3.8,63.3
EST-157,Economía,Diurna,No,18.1,78.2,6.2,62.5
EST-158,Enfermería,Diurna,Sí,5.3,92.0,6.8,56.4
EST-159,Enfermería,Diurna,No,13.0,78.8,5.3,54.6
EST-160,Economía,Diurna,No,18.9,89.7,6.2,80.1
'''

VENTAS_CSV = '''Sucursal,Ciudad,Categoria,Canal,Inversion_publicidad_kUSD,Precio_medio_USD,Visitas_miles,Ventas_kUSD
SUC-001,Quito,Tecnología,Tienda física,29.6,248.25,16.07,108.0
SUC-002,Quito,Vestuario,Online,56.0,56.51,23.22,194.08
SUC-003,Manta,Vestuario,Tienda física,20.5,58.88,13.82,81.22
SUC-004,Cuenca,Alimentos,Tienda física,35.5,26.25,24.39,147.64
SUC-005,Guayaquil,Alimentos,Online,19.9,22.4,7.54,101.15
SUC-006,Cuenca,Vestuario,Tienda física,98.4,46.21,39.09,287.54
SUC-007,Cuenca,Hogar,Mixto,64.3,115.32,21.78,205.67
SUC-008,Quito,Tecnología,Mixto,47.7,195.28,25.8,205.92
SUC-009,Guayaquil,Hogar,Tienda física,42.8,127.21,20.82,162.04
SUC-010,Quito,Hogar,Online,62.1,105.89,28.84,222.38
SUC-011,Cuenca,Hogar,Mixto,56.7,87.98,30.96,210.75
SUC-012,Quito,Hogar,Tienda física,45.0,90.69,22.78,173.27
SUC-013,Cuenca,Vestuario,Mixto,32.5,43.22,14.03,129.08
SUC-014,Cuenca,Tecnología,Tienda física,41.9,342.53,21.22,168.72
SUC-015,Guayaquil,Tecnología,Tienda física,85.8,221.67,32.08,277.34
SUC-016,Guayaquil,Hogar,Tienda física,53.1,126.01,28.46,194.1
SUC-017,Manta,Hogar,Mixto,53.0,79.0,22.82,202.31
SUC-018,Manta,Hogar,Mixto,47.0,103.42,20.35,173.54
SUC-019,Cuenca,Vestuario,Mixto,39.8,57.7,18.67,173.15
SUC-020,Quito,Tecnología,Mixto,34.8,340.48,21.35,151.32
SUC-021,Cuenca,Vestuario,Online,8.7,68.96,10.91,84.97
SUC-022,Manta,Hogar,Online,50.6,116.4,24.92,186.89
SUC-023,Loja,Vestuario,Tienda física,33.4,39.47,19.13,119.2
SUC-024,Guayaquil,Alimentos,Online,57.5,21.82,20.89,208.38
SUC-025,Manta,Tecnología,Tienda física,63.8,299.47,28.58,198.23
SUC-026,Quito,Hogar,Mixto,26.4,125.64,14.47,128.56
SUC-027,Quito,Alimentos,Online,48.6,19.68,21.72,158.94
SUC-028,Cuenca,Hogar,Tienda física,34.5,95.23,21.6,144.17
SUC-029,Manta,Hogar,Tienda física,16.9,70.52,7.73,78.08
SUC-030,Manta,Tecnología,Online,67.4,348.32,31.51,236.99
SUC-031,Cuenca,Vestuario,Tienda física,35.0,52.66,21.56,145.56
SUC-032,Cuenca,Alimentos,Tienda física,39.5,23.99,19.32,123.91
SUC-033,Guayaquil,Tecnología,Online,63.9,336.17,28.84,242.96
SUC-034,Manta,Vestuario,Mixto,47.7,55.55,17.89,161.36
SUC-035,Quito,Tecnología,Tienda física,59.1,347.91,31.52,238.68
SUC-036,Loja,Vestuario,Tienda física,65.3,46.47,27.18,206.26
SUC-037,Loja,Vestuario,Tienda física,44.5,44.96,28.33,159.1
SUC-038,Quito,Alimentos,Online,26.9,19.86,16.01,125.23
SUC-039,Quito,Vestuario,Tienda física,27.6,70.47,21.93,125.84
SUC-040,Manta,Alimentos,Tienda física,39.5,18.37,17.43,127.76
SUC-041,Loja,Vestuario,Online,68.7,59.37,30.34,251.36
SUC-042,Loja,Tecnología,Mixto,9.2,362.24,8.44,66.95
SUC-043,Guayaquil,Alimentos,Online,63.2,18.67,32.57,257.01
SUC-044,Loja,Hogar,Mixto,26.4,127.7,15.53,133.8
SUC-045,Guayaquil,Vestuario,Tienda física,41.8,60.56,21.39,171.74
SUC-046,Quito,Vestuario,Online,47.2,22.28,27.56,210.25
SUC-047,Quito,Tecnología,Tienda física,20.6,379.97,9.48,87.65
SUC-048,Manta,Vestuario,Tienda física,48.3,63.48,21.28,156.43
SUC-049,Cuenca,Alimentos,Online,61.2,17.12,29.53,205.69
SUC-050,Quito,Vestuario,Mixto,65.1,50.25,29.93,244.93
SUC-051,Loja,Vestuario,Mixto,29.4,45.75,17.86,121.68
SUC-052,Loja,Vestuario,Mixto,42.0,45.46,22.55,148.42
SUC-053,Manta,Alimentos,Mixto,53.4,13.33,25.03,216.32
SUC-054,Manta,Vestuario,Tienda física,71.2,56.82,28.48,212.03
SUC-055,Guayaquil,Vestuario,Online,41.2,46.07,22.18,172.44
SUC-056,Cuenca,Tecnología,Mixto,48.8,448.46,27.82,201.46
SUC-057,Quito,Tecnología,Online,37.5,262.93,27.03,170.34
SUC-058,Manta,Alimentos,Tienda física,63.8,17.63,32.87,226.98
SUC-059,Quito,Alimentos,Tienda física,69.0,11.98,35.67,239.69
SUC-060,Cuenca,Alimentos,Tienda física,36.8,31.75,17.5,127.77
SUC-061,Guayaquil,Alimentos,Online,52.3,18.27,28.11,218.86
SUC-062,Manta,Alimentos,Online,18.5,13.76,12.56,96.92
SUC-063,Quito,Alimentos,Tienda física,44.4,16.92,25.91,158.67
SUC-064,Cuenca,Vestuario,Tienda física,7.0,49.93,12.53,53.87
SUC-065,Quito,Hogar,Mixto,55.6,104.39,17.15,206.21
SUC-066,Cuenca,Hogar,Mixto,50.7,85.59,24.31,182.55
SUC-067,Guayaquil,Alimentos,Tienda física,54.2,19.29,27.0,211.24
SUC-068,Loja,Tecnología,Mixto,37.5,425.84,18.02,143.82
SUC-069,Cuenca,Alimentos,Mixto,50.8,22.22,26.75,216.98
SUC-070,Quito,Tecnología,Tienda física,20.9,264.08,15.95,93.29
SUC-071,Quito,Tecnología,Mixto,37.5,346.07,21.72,177.98
SUC-072,Quito,Hogar,Tienda física,31.4,120.57,18.31,128.55
SUC-073,Cuenca,Vestuario,Tienda física,64.2,58.63,25.8,221.26
SUC-074,Cuenca,Hogar,Mixto,50.8,113.67,33.11,205.12
SUC-075,Cuenca,Vestuario,Online,30.9,61.44,12.5,102.23
SUC-076,Loja,Hogar,Mixto,64.7,96.13,34.44,231.37
SUC-077,Loja,Vestuario,Mixto,30.1,59.79,11.52,112.31
SUC-078,Cuenca,Hogar,Tienda física,57.5,93.15,35.23,209.75
SUC-079,Cuenca,Vestuario,Mixto,51.5,61.81,24.32,199.57
SUC-080,Manta,Alimentos,Mixto,48.0,15.45,22.05,176.63
SUC-081,Guayaquil,Hogar,Mixto,50.0,111.4,23.62,199.49
SUC-082,Cuenca,Tecnología,Tienda física,45.7,330.71,22.85,156.22
SUC-083,Quito,Tecnología,Tienda física,39.9,327.91,19.52,143.33
SUC-084,Cuenca,Alimentos,Mixto,58.8,21.01,25.69,205.51
SUC-085,Quito,Vestuario,Tienda física,20.8,58.93,12.07,84.42
SUC-086,Manta,Tecnología,Tienda física,53.8,320.65,26.48,213.44
SUC-087,Guayaquil,Hogar,Mixto,44.1,128.01,26.75,222.58
SUC-088,Cuenca,Alimentos,Tienda física,37.0,21.36,20.87,155.22
SUC-089,Cuenca,Tecnología,Tienda física,40.3,290.54,21.09,135.81
SUC-090,Manta,Alimentos,Online,31.9,20.08,19.49,135.37
SUC-091,Guayaquil,Tecnología,Online,56.5,353.99,22.34,211.64
SUC-092,Quito,Alimentos,Online,56.1,17.12,28.22,241.93
SUC-093,Cuenca,Alimentos,Online,31.8,19.14,15.44,120.48
SUC-094,Manta,Tecnología,Tienda física,57.3,473.94,19.76,179.87
SUC-095,Guayaquil,Alimentos,Mixto,31.5,18.85,22.9,161.88
SUC-096,Loja,Hogar,Tienda física,49.4,81.19,31.54,191.15
SUC-097,Cuenca,Hogar,Mixto,39.7,80.85,18.55,158.19
SUC-098,Loja,Hogar,Mixto,45.0,101.55,25.7,173.96
SUC-099,Loja,Vestuario,Tienda física,33.9,63.7,20.98,137.68
SUC-100,Cuenca,Hogar,Tienda física,50.3,95.63,27.7,198.12
SUC-101,Manta,Vestuario,Online,60.4,67.07,23.93,187.65
SUC-102,Loja,Tecnología,Tienda física,49.8,346.71,24.3,173.57
SUC-103,Guayaquil,Vestuario,Online,39.7,46.5,17.6,162.38
SUC-104,Quito,Alimentos,Mixto,24.5,23.25,18.18,147.28
SUC-105,Quito,Tecnología,Online,50.0,301.86,29.49,244.2
SUC-106,Loja,Alimentos,Tienda física,45.0,31.75,21.65,136.87
SUC-107,Loja,Hogar,Online,45.5,88.93,23.77,156.0
SUC-108,Guayaquil,Vestuario,Mixto,52.1,53.92,25.94,197.46
SUC-109,Loja,Vestuario,Tienda física,32.5,44.86,22.55,137.7
SUC-110,Loja,Vestuario,Tienda física,49.8,54.76,21.34,155.56
SUC-111,Cuenca,Hogar,Tienda física,58.8,88.22,26.41,196.07
SUC-112,Cuenca,Hogar,Mixto,35.4,93.37,20.96,143.77
SUC-113,Quito,Vestuario,Mixto,46.1,45.5,20.71,174.51
SUC-114,Guayaquil,Alimentos,Mixto,46.1,22.25,28.03,189.83
SUC-115,Manta,Hogar,Mixto,57.4,89.8,25.62,198.47
SUC-116,Loja,Vestuario,Tienda física,53.7,57.34,24.17,200.58
SUC-117,Quito,Tecnología,Tienda física,67.4,219.89,28.91,217.84
SUC-118,Loja,Alimentos,Tienda física,66.1,27.0,26.31,213.09
SUC-119,Loja,Hogar,Tienda física,31.3,111.51,11.39,93.03
SUC-120,Cuenca,Alimentos,Tienda física,39.3,20.88,18.22,149.37
SUC-121,Manta,Tecnología,Tienda física,28.1,319.26,14.78,108.85
SUC-122,Manta,Alimentos,Online,53.4,18.89,29.77,172.53
SUC-123,Quito,Alimentos,Tienda física,21.4,15.34,14.48,102.7
SUC-124,Manta,Alimentos,Online,30.7,26.03,15.88,129.68
SUC-125,Guayaquil,Vestuario,Tienda física,59.0,56.64,21.15,189.23
SUC-126,Cuenca,Hogar,Online,73.4,123.95,33.25,254.75
SUC-127,Manta,Tecnología,Tienda física,44.8,301.44,21.72,160.7
SUC-128,Quito,Alimentos,Tienda física,53.2,21.41,29.1,179.77
SUC-129,Guayaquil,Tecnología,Mixto,29.1,357.37,15.23,118.29
SUC-130,Loja,Hogar,Mixto,73.3,100.07,29.27,237.23
SUC-131,Cuenca,Alimentos,Online,31.0,25.58,18.85,136.39
SUC-132,Manta,Tecnología,Mixto,65.9,230.53,26.94,216.7
SUC-133,Guayaquil,Hogar,Tienda física,52.5,111.7,33.05,216.71
SUC-134,Loja,Vestuario,Mixto,39.8,53.99,17.57,182.39
SUC-135,Cuenca,Hogar,Tienda física,53.0,89.4,23.41,176.29
SUC-136,Guayaquil,Tecnología,Mixto,29.9,310.96,21.46,159.72
SUC-137,Manta,Tecnología,Tienda física,39.8,317.61,20.34,131.16
SUC-138,Manta,Alimentos,Online,36.3,21.64,17.8,128.77
SUC-139,Loja,Tecnología,Tienda física,27.5,335.74,10.87,91.42
SUC-140,Guayaquil,Alimentos,Online,30.7,30.88,21.15,136.56
SUC-141,Manta,Tecnología,Online,49.3,229.06,20.41,177.61
SUC-142,Cuenca,Vestuario,Online,38.8,45.47,30.93,182.33
SUC-143,Loja,Alimentos,Online,36.0,26.84,24.53,154.31
SUC-144,Guayaquil,Hogar,Mixto,26.4,96.36,19.64,141.07
SUC-145,Quito,Vestuario,Mixto,25.1,50.38,19.5,106.12
SUC-146,Cuenca,Hogar,Tienda física,65.9,99.39,29.91,224.65
SUC-147,Cuenca,Hogar,Tienda física,43.1,101.59,20.01,151.41
SUC-148,Guayaquil,Vestuario,Mixto,64.3,48.96,27.18,207.61
SUC-149,Loja,Hogar,Tienda física,32.5,83.01,17.6,105.63
SUC-150,Cuenca,Vestuario,Tienda física,54.1,47.23,27.96,211.33
'''

AIRE_CSV = '''Registro,Ciudad,Zona,Estacion_del_ano,Trafico_veh_hora,Temp_media_C,Humedad_pct,Viento_km_h,PM25_ug_m3
AIR-001,Quito,Industrial,Invierno,2180,9.9,56.4,6.4,65.1
AIR-002,Cuenca,Céntrica,Verano,874,20.5,70.0,7.6,34.0
AIR-003,Guayaquil,Céntrica,Verano,1577,28.4,72.1,5.0,45.2
AIR-004,Quito,Periurbana,Otoño,532,17.4,78.8,6.4,23.5
AIR-005,Cuenca,Céntrica,Invierno,2140,12.6,65.1,2.6,59.3
AIR-006,Guayaquil,Residencial,Primavera,721,18.0,68.0,8.6,27.5
AIR-007,Cuenca,Residencial,Invierno,482,16.4,59.0,7.5,30.5
AIR-008,Loja,Residencial,Invierno,844,11.3,76.1,14.1,33.0
AIR-009,Manta,Residencial,Primavera,1108,17.8,80.1,13.6,34.0
AIR-010,Loja,Residencial,Otoño,674,21.3,90.2,14.3,27.1
AIR-011,Cuenca,Céntrica,Verano,1223,25.6,72.6,17.4,27.3
AIR-012,Manta,Industrial,Verano,1366,25.1,64.8,10.9,45.1
AIR-013,Quito,Periurbana,Verano,239,26.9,67.9,16.1,14.3
AIR-014,Loja,Residencial,Verano,734,27.0,72.3,7.7,25.5
AIR-015,Loja,Industrial,Verano,1536,26.9,68.1,16.1,43.8
AIR-016,Loja,Céntrica,Invierno,1694,16.3,78.9,13.6,46.1
AIR-017,Loja,Periurbana,Primavera,420,17.0,66.2,10.7,22.9
AIR-018,Guayaquil,Residencial,Invierno,728,12.9,81.3,13.6,31.2
AIR-019,Cuenca,Residencial,Primavera,938,22.7,50.6,6.0,32.8
AIR-020,Quito,Céntrica,Otoño,1755,17.8,56.7,4.9,53.9
AIR-021,Cuenca,Residencial,Primavera,922,16.8,54.9,13.9,34.1
AIR-022,Manta,Periurbana,Verano,449,24.1,51.7,20.1,15.1
AIR-023,Cuenca,Industrial,Verano,1174,28.7,61.1,5.5,41.3
AIR-024,Loja,Industrial,Invierno,1426,13.5,60.4,5.6,53.8
AIR-025,Cuenca,Residencial,Verano,847,24.9,69.9,14.7,26.4
AIR-026,Guayaquil,Industrial,Invierno,939,18.4,54.4,16.0,42.8
AIR-027,Loja,Residencial,Primavera,625,18.3,81.4,10.0,28.1
AIR-028,Quito,Residencial,Primavera,622,25.8,50.7,12.7,26.7
AIR-029,Quito,Residencial,Verano,645,26.9,56.0,12.0,20.7
AIR-030,Loja,Residencial,Invierno,534,15.0,69.3,14.0,32.3
AIR-031,Manta,Industrial,Invierno,1358,16.1,72.2,7.3,47.3
AIR-032,Quito,Residencial,Primavera,618,12.7,63.2,10.5,29.8
AIR-033,Guayaquil,Residencial,Primavera,705,19.0,82.3,8.5,20.8
AIR-034,Manta,Céntrica,Invierno,2367,12.8,93.9,12.4,56.7
AIR-035,Loja,Periurbana,Primavera,262,20.0,57.6,16.6,18.6
AIR-036,Quito,Residencial,Otoño,770,14.9,41.6,7.2,32.4
AIR-037,Loja,Residencial,Invierno,801,12.4,59.9,4.0,40.6
AIR-038,Manta,Periurbana,Verano,416,26.2,73.4,11.6,20.2
AIR-039,Cuenca,Industrial,Invierno,1766,17.5,51.7,5.5,59.1
AIR-040,Manta,Periurbana,Primavera,438,19.2,70.7,8.8,24.4
AIR-041,Cuenca,Periurbana,Invierno,504,15.9,73.5,7.3,32.2
AIR-042,Guayaquil,Céntrica,Primavera,1042,20.0,58.7,8.9,37.9
AIR-043,Cuenca,Periurbana,Invierno,484,15.4,46.2,11.5,30.6
AIR-044,Guayaquil,Periurbana,Invierno,506,16.4,75.0,10.1,27.8
AIR-045,Guayaquil,Residencial,Otoño,922,20.3,70.7,12.7,33.6
AIR-046,Cuenca,Céntrica,Verano,1688,26.1,56.2,10.1,40.5
AIR-047,Cuenca,Residencial,Invierno,629,13.7,63.6,9.1,27.8
AIR-048,Cuenca,Céntrica,Otoño,1670,16.9,67.7,16.7,36.7
AIR-049,Manta,Periurbana,Otoño,388,20.2,66.3,13.2,20.9
AIR-050,Cuenca,Céntrica,Primavera,1394,15.5,79.2,10.7,39.7
AIR-051,Cuenca,Céntrica,Otoño,1679,21.1,62.6,11.3,45.5
AIR-052,Quito,Periurbana,Verano,527,23.5,72.5,3.6,23.5
AIR-053,Cuenca,Residencial,Otoño,625,19.9,53.9,18.7,28.2
AIR-054,Cuenca,Residencial,Otoño,632,15.9,61.0,11.6,28.9
AIR-055,Manta,Céntrica,Otoño,1924,16.4,73.5,10.9,43.9
AIR-056,Guayaquil,Industrial,Verano,1074,28.9,63.0,13.4,35.4
AIR-057,Quito,Céntrica,Otoño,1455,17.0,47.0,8.8,48.9
AIR-058,Quito,Industrial,Verano,1182,25.2,73.3,9.5,40.4
AIR-059,Quito,Industrial,Primavera,1328,22.9,48.5,8.3,42.9
AIR-060,Cuenca,Industrial,Otoño,880,22.5,48.0,17.9,39.1
AIR-061,Manta,Industrial,Otoño,1293,17.1,58.4,14.4,44.0
AIR-062,Guayaquil,Residencial,Otoño,926,17.8,67.9,8.3,29.7
AIR-063,Quito,Residencial,Invierno,1002,12.6,64.9,10.1,41.6
AIR-064,Loja,Periurbana,Otoño,366,20.5,86.0,14.4,15.6
AIR-065,Guayaquil,Céntrica,Otoño,1303,18.6,74.4,5.9,42.2
AIR-066,Loja,Periurbana,Primavera,282,19.4,74.4,12.9,16.7
AIR-067,Cuenca,Periurbana,Invierno,284,14.7,71.9,9.4,28.4
AIR-068,Loja,Periurbana,Verano,377,22.6,58.1,15.5,20.5
AIR-069,Guayaquil,Industrial,Primavera,837,24.3,64.0,8.9,42.1
AIR-070,Manta,Industrial,Invierno,1977,12.2,66.8,10.2,55.2
AIR-071,Quito,Industrial,Primavera,1642,19.8,58.0,11.8,43.1
AIR-072,Quito,Periurbana,Verano,433,29.0,51.7,11.5,17.4
AIR-073,Guayaquil,Residencial,Primavera,780,20.2,48.3,2.3,30.3
AIR-074,Guayaquil,Residencial,Otoño,978,21.0,41.6,7.8,32.5
AIR-075,Cuenca,Periurbana,Otoño,409,20.2,67.2,12.7,20.3
AIR-076,Loja,Industrial,Otoño,1781,16.5,87.9,10.3,49.9
AIR-077,Quito,Céntrica,Verano,1842,23.0,66.9,18.7,38.1
AIR-078,Manta,Periurbana,Primavera,369,21.4,75.3,10.1,23.8
AIR-079,Loja,Periurbana,Invierno,318,15.3,79.4,8.1,28.7
AIR-080,Quito,Periurbana,Verano,302,18.4,69.0,16.2,13.5
AIR-081,Guayaquil,Residencial,Invierno,751,11.7,63.9,6.4,39.7
AIR-082,Manta,Residencial,Primavera,647,18.1,60.5,8.8,34.2
AIR-083,Cuenca,Industrial,Primavera,1399,17.5,42.1,8.9,41.8
AIR-084,Cuenca,Céntrica,Primavera,2221,18.9,54.3,13.2,51.9
AIR-085,Cuenca,Periurbana,Invierno,373,15.0,82.3,17.0,20.0
AIR-086,Quito,Industrial,Verano,1317,23.3,68.6,7.2,40.5
AIR-087,Manta,Periurbana,Invierno,441,16.7,65.7,11.0,32.0
AIR-088,Quito,Periurbana,Otoño,440,19.2,80.0,13.3,24.3
AIR-089,Manta,Periurbana,Otoño,458,21.9,54.9,12.8,23.5
AIR-090,Quito,Residencial,Otoño,933,19.5,74.5,11.2,28.5
AIR-091,Quito,Industrial,Primavera,1920,15.1,77.4,3.9,49.8
AIR-092,Cuenca,Residencial,Verano,584,21.8,70.0,10.9,25.5
AIR-093,Loja,Periurbana,Verano,522,21.8,78.5,6.5,23.0
AIR-094,Loja,Céntrica,Invierno,1682,18.8,78.6,8.1,53.3
AIR-095,Manta,Residencial,Invierno,708,16.0,40.0,14.0,33.2
AIR-096,Guayaquil,Residencial,Invierno,685,19.6,88.1,18.0,31.0
AIR-097,Quito,Industrial,Otoño,1759,21.3,82.9,4.2,51.5
AIR-098,Quito,Industrial,Primavera,1478,19.0,77.6,12.1,46.2
AIR-099,Quito,Periurbana,Otoño,496,18.8,64.4,8.5,22.0
AIR-100,Quito,Céntrica,Otoño,1641,17.9,70.9,15.8,42.6
AIR-101,Cuenca,Industrial,Verano,1321,26.4,58.5,10.1,41.4
AIR-102,Loja,Céntrica,Otoño,1445,18.2,62.9,10.8,45.1
AIR-103,Loja,Industrial,Primavera,1356,18.4,78.3,13.6,37.3
AIR-104,Cuenca,Industrial,Verano,1411,25.8,69.2,13.3,41.7
AIR-105,Manta,Periurbana,Verano,479,23.0,61.9,13.1,13.2
AIR-106,Cuenca,Residencial,Invierno,511,14.4,63.2,17.5,25.0
AIR-107,Loja,Periurbana,Otoño,585,23.1,53.3,19.6,26.4
AIR-108,Quito,Periurbana,Verano,535,25.0,93.4,6.9,19.7
AIR-109,Quito,Residencial,Invierno,833,16.8,65.8,13.4,38.9
AIR-110,Quito,Céntrica,Invierno,1173,13.1,84.6,14.6,38.8
AIR-111,Manta,Industrial,Primavera,1386,15.1,78.9,11.9,45.0
AIR-112,Manta,Industrial,Invierno,2097,10.4,57.3,14.8,55.8
AIR-113,Loja,Periurbana,Primavera,395,22.5,53.4,10.0,18.7
AIR-114,Guayaquil,Periurbana,Primavera,346,24.1,61.4,5.9,20.2
AIR-115,Loja,Industrial,Verano,1535,22.6,73.3,8.0,45.7
AIR-116,Manta,Residencial,Primavera,765,24.5,46.7,16.8,25.4
AIR-117,Guayaquil,Periurbana,Primavera,242,18.2,56.5,18.3,11.7
AIR-118,Quito,Periurbana,Invierno,434,12.0,61.6,10.6,31.0
AIR-119,Manta,Residencial,Verano,741,30.1,73.9,4.7,27.5
AIR-120,Guayaquil,Residencial,Verano,941,22.4,76.4,13.4,25.3
AIR-121,Manta,Céntrica,Primavera,1741,17.3,64.4,11.1,45.2
AIR-122,Manta,Residencial,Verano,606,25.6,74.3,14.4,23.4
AIR-123,Cuenca,Céntrica,Verano,1981,24.0,67.2,15.9,43.9
AIR-124,Manta,Industrial,Invierno,1512,14.1,95.7,19.3,47.1
AIR-125,Manta,Céntrica,Invierno,1750,13.7,65.6,12.1,52.3
AIR-126,Cuenca,Industrial,Primavera,2333,19.9,62.7,7.0,56.9
AIR-127,Quito,Residencial,Primavera,1069,19.0,64.8,14.0,30.7
AIR-128,Manta,Industrial,Invierno,1184,14.0,60.7,7.5,51.4
AIR-129,Manta,Céntrica,Otoño,1047,16.6,64.7,7.7,37.9
AIR-130,Quito,Residencial,Verano,649,24.1,94.8,10.9,26.9
AIR-131,Loja,Residencial,Otoño,817,18.5,43.5,12.9,26.5
AIR-132,Cuenca,Industrial,Primavera,1822,16.5,69.0,11.8,49.8
AIR-133,Guayaquil,Industrial,Primavera,1907,22.3,80.7,8.2,53.7
AIR-134,Manta,Céntrica,Otoño,1879,15.9,65.8,21.2,43.1
AIR-135,Guayaquil,Céntrica,Verano,1889,25.5,62.5,11.0,45.3
AIR-136,Manta,Periurbana,Invierno,324,13.7,69.1,15.2,28.4
AIR-137,Loja,Industrial,Verano,1791,24.7,39.8,2.5,51.7
AIR-138,Quito,Céntrica,Invierno,1786,15.1,80.9,9.7,50.8
AIR-139,Guayaquil,Céntrica,Verano,1697,29.6,76.6,14.2,39.2
AIR-140,Cuenca,Periurbana,Primavera,432,17.9,58.4,13.7,21.1
AIR-141,Loja,Residencial,Verano,620,24.1,60.4,10.3,23.3
AIR-142,Loja,Industrial,Primavera,1308,12.4,82.2,5.0,43.0
AIR-143,Cuenca,Residencial,Invierno,1011,12.9,70.7,23.7,30.6
AIR-144,Manta,Industrial,Primavera,1321,17.5,85.1,12.4,41.0
AIR-145,Quito,Céntrica,Verano,1449,21.9,80.3,13.8,39.1
AIR-146,Cuenca,Residencial,Otoño,686,24.0,72.8,10.8,27.5
AIR-147,Quito,Céntrica,Otoño,2323,18.0,61.9,8.2,58.4
AIR-148,Loja,Céntrica,Verano,1347,25.9,53.7,10.1,38.1
AIR-149,Manta,Céntrica,Primavera,1837,19.6,74.2,9.9,43.4
AIR-150,Cuenca,Industrial,Otoño,1115,17.3,67.5,5.4,41.9
'''

SAMPLES = [
    {
        "key": "cultivos",
        "name": "rendimiento_cultivos.csv",
        "title": "Rendimiento de cultivos",
        "area": "Agronomía",
        "description": "Parcelas agrícolas con riego, fertilización y clima. El fertilizante explica la mayor parte del rendimiento.",
        "rows": 140,
        "columns": 9,
        "numeric": 5,
        "categorical": 4,
        "target": "Rendimiento_ton_ha",
        "driver": "Fertilizante_kg_ha",
        "csv": CULTIVOS_CSV,
    },
    {
        "key": "salud",
        "name": "salud_cardiovascular.csv",
        "title": "Chequeo cardiovascular",
        "area": "Salud",
        "description": "Pacientes con edad, IMC, colesterol y horas de sueño frente a la presión sistólica. La edad es el predictor dominante.",
        "rows": 150,
        "columns": 9,
        "numeric": 5,
        "categorical": 4,
        "target": "Presion_sistolica",
        "driver": "Edad",
        "csv": SALUD_CSV,
    },
    {
        "key": "educacion",
        "name": "rendimiento_academico.csv",
        "title": "Rendimiento académico",
        "area": "Educación",
        "description": "Estudiantes con horas de estudio, asistencia y tiempo de pantalla frente al puntaje final sobre 100.",
        "rows": 160,
        "columns": 8,
        "numeric": 4,
        "categorical": 4,
        "target": "Puntaje_final",
        "driver": "Horas_estudio_sem",
        "csv": EDUCACION_CSV,
    },
    {
        "key": "ventas",
        "name": "ventas_retail.csv",
        "title": "Ventas de retail",
        "area": "Economía",
        "description": "Sucursales con inversión publicitaria, precio medio y tráfico de clientes frente a las ventas mensuales en miles de USD.",
        "rows": 150,
        "columns": 8,
        "numeric": 4,
        "categorical": 4,
        "target": "Ventas_kUSD",
        "driver": "Inversion_publicidad_kUSD",
        "csv": VENTAS_CSV,
    },
    {
        "key": "aire",
        "name": "calidad_aire.csv",
        "title": "Calidad del aire",
        "area": "Medio ambiente",
        "description": "Mediciones de estaciones urbanas: tráfico, viento y humedad frente a la concentración de PM2.5.",
        "rows": 150,
        "columns": 9,
        "numeric": 5,
        "categorical": 4,
        "target": "PM25_ug_m3",
        "driver": "Trafico_veh_hora",
        "csv": AIRE_CSV,
    },
]


SAMPLE_INDEX = {item["key"]: item for item in SAMPLES}
DEFAULT_SAMPLE = SAMPLES[0]["key"]

# Back-compat aliases: the first dataset is the one loaded when no key is given.
SAMPLE_NAME = SAMPLES[0]["name"]
SAMPLE_CSV = SAMPLES[0]["csv"]


def catalog() -> list[dict]:
    """Metadata for every dataset, without the CSV payloads."""
    return [
        {key: value for key, value in item.items() if key != "csv"}
        for item in SAMPLES
    ]


def get(key: str | None = None) -> dict | None:
    """Look up one dataset by key; None when the key is unknown."""
    return SAMPLE_INDEX.get(key or DEFAULT_SAMPLE)
