"""Generate the bundled sample dataset (deterministic).

Writes both `sample_data/rendimiento_cultivos.csv` (a file users can re-upload)
and `core/sample.py` (embedded, so the browser build needs no extra fetch).

Run:  python scripts/make_sample.py
"""

from __future__ import annotations

import csv
import io
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

REGIONS = ["Norte", "Centro", "Sur", "Litoral"]
VARIETIES = ["Aurora", "Sembra", "Kirán"]
IRRIGATION = ["Goteo", "Aspersión", "Gravedad"]

HEADER = [
    "Parcela",
    "Region",
    "Variedad",
    "Riego",
    "Riego_mm",
    "Fertilizante_kg_ha",
    "Temp_media_C",
    "Horas_sol",
    "Rendimiento_ton_ha",
]


def build_rows(n: int = 140, seed: int = 20260808) -> list[list[object]]:
    rng = random.Random(seed)
    rows: list[list[object]] = [HEADER]

    for i in range(n):
        region = rng.choice(REGIONS)
        variety = rng.choice(VARIETIES)
        irrigation = rng.choice(IRRIGATION)

        # Regional baselines keep the categorical columns informative.
        base_water = {"Norte": 380, "Centro": 460, "Sur": 520, "Litoral": 600}[region]
        water = round(rng.gauss(base_water, 70), 1)
        water = max(180.0, water)

        fertiliser = round(max(20.0, rng.gauss(160, 42)), 1)
        temperature = round(rng.gauss({"Norte": 17.5, "Centro": 20.0,
                                       "Sur": 22.5, "Litoral": 24.0}[region], 1.9), 1)
        sunshine = round(max(3.5, rng.gauss(7.6, 1.15)), 2)

        variety_bonus = {"Aurora": 0.0, "Sembra": 0.28, "Kirán": -0.18}[variety]

        # Fertiliser is the dominant driver (strong fit, R² ~0.76) while water,
        # sunshine and temperature are only weakly predictive on their own. That
        # spread gives each variable pairing a visibly different result, with
        # mild diminishing returns so the relationship is not perfectly linear.
        yield_ton = (
            0.85
            + 0.0225 * fertiliser
            - 0.0000175 * fertiliser * fertiliser
            + 0.0034 * water
            - 0.0000011 * water * water
            + 0.132 * sunshine
            + variety_bonus
            + rng.gauss(0, 0.22)
        )
        yield_ton = round(max(0.6, yield_ton), 2)

        rows.append([
            f"P-{i + 1:03d}",
            region,
            variety,
            irrigation,
            water,
            fertiliser,
            temperature,
            sunshine,
            yield_ton,
        ])

    return rows


def to_csv(rows: list[list[object]]) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerows(rows)
    return buffer.getvalue()


def main() -> None:
    rows = build_rows()
    text = to_csv(rows)

    csv_path = ROOT / "sample_data" / "rendimiento_cultivos.csv"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    csv_path.write_text(text, encoding="utf-8")

    module = ROOT / "core" / "sample.py"
    module.write_text(
        '"""Bundled sample dataset — generated by scripts/make_sample.py.\n\n'
        "Embedded as a module so the Pyodide build can load a demo dataset\n"
        "without a second network request. Do not edit by hand.\n"
        '"""\n\n'
        'SAMPLE_NAME = "rendimiento_cultivos.csv"\n\n'
        "SAMPLE_CSV = '''" + text + "'''\n",
        encoding="utf-8",
    )

    print(f"wrote {csv_path.relative_to(ROOT)}  ({len(rows) - 1} rows)")
    print(f"wrote {module.relative_to(ROOT)}    ({len(text)} bytes)")


if __name__ == "__main__":
    main()
